config/routes.rb
DrillsBook::Application.routes.draw do

  get "repeats/create"
  get "home/index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'users/:user_id/trainings/:date', to: 'trainings#index', date: /\d{4}-\d{2}-\d{2}/
  get 'trainings/:id', to: 'trainings#show', as: 'training', id: /\d+/

  resources :repeats, only: :create
  resources :daily_exercises, except: [:show, :edit, :update]

  resources :users do
    resources :trainings, except: :show
  end
  resources :training_exercises
  resources :exercises, path: 'wiki/exercises'
  resources :elements, path: 'wiki/elements'

  root 'home#index'

  

end

app/models/apparatus.rb
class Apparatus < ActiveRecord::Base
  has_many :exercises

  validates :name, :uniqueness => true
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_and_belongs_to_many :elements
end

app/models/daily_exercise.rb
class DailyExercise < ActiveRecord::Base
    belongs_to :user
    belongs_to :exercise
end

app/models/element.rb
require 'file_size_validator'
class Element < ActiveRecord::Base
    before_validation :default_values
    has_many :exercises
    has_and_belongs_to_many :categories
    has_and_belongs_to_many :muscle_groups
    belongs_to :user
    belongs_to :scope
    mount_uploader :image, ImageUploader
    validates :image,
        :presence => false,
        :file_size => { :maximum => 1.megabytes.to_i }

    def default_values
        self.scope_id ||= Scope.where(:name => 'user_private').first.id
        self.description ||= ''
    end
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  before_validation :default_values
  has_many :training_exercises, dependent: :destroy
  has_many :daily_exercises, dependent: :destroy
  has_many :trainings, through: :training_exercises
  belongs_to :element
  belongs_to :user
  belongs_to :apparatus

  def self.get_or_create_by(user, element_name, apparatus_name, options = {})
    element = Element.find_or_create_by(name: element_name)
    apparatus = Apparatus.where(name: apparatus_name).first
    if options[:hold] == '1'
      options[:hold] = true
    elsif
      options[:hold] = false
    end
    options[:user_id] = user.id
    options[:element_id] = element.id
    options[:apparatus_id] = apparatus.id
 #   Exercise.where(options).first
    Exercise.find_or_create_by(options)
  end

  def element_name
    element.try(:name)
  end

  def element_name=(name)
    if name.strip == ''
        return nil
    end
    self.element = Element.find_or_create_by(:name => name) if name.present?
  end

  def apparatus_name
    apparatus.try(:name)
  end

  def apparatus_name=(name)
    self.apparatus = Apparatus.where(:name => name).first if name.present?
  end

  def default_values
      self.load ||= 0
      self.length ||= 0
      self.number_of_reps_in_set ||= 0
      self.number_of_sets ||= 0
      self.description ||= ''
      self.hold ||= false
      true
  end
end

app/models/muscle.rb
class Muscle < ActiveRecord::Base
    has_and_belongs_to_many :muscle_groups
end

app/models/muscle_group.rb
class MuscleGroup < ActiveRecord::Base
    has_and_belongs_to_many :muscles
    has_and_belongs_to_many :elements
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users

  validates :name, :uniqueness => true
end

app/models/scope.rb
class Scope < ActiveRecord::Base
  has_many :elements

  validates :name, :uniqueness => true
end

app/models/training.rb
class Training < ActiveRecord::Base
    has_many :training_types
    has_many :training_exercises, dependent: :destroy
    has_many :exercises, through: :training_exercises
    belongs_to :user
end

app/models/training_exercise.rb
class TrainingExercise < ActiveRecord::Base
    belongs_to :training
    belongs_to :exercise
end

app/models/training_type.rb
class TrainingType < ActiveRecord::Base
    has_and_belongs_to_many :trainings
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :default_values
  has_many :trainings
  has_many :exercises
  has_many :elements
  has_many :daily_exercises, dependent: :destroy
  belongs_to :role

  validates :role, :presence => true

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def default_values
    self.role_id ||= Role.where(:name => 'user').first.id
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]

  def create
    @training = Training.create(training_params)
    @training.user_id = current_user.id
    if @training.save
      flash[:notice] = 'Successfully created new training.'
      redirect_to user_training_path(current_user, @training.start.to_date)
    else
      redirect_to user_training_path(current_user, Date.parse(params[:id]))
    end
  end

  def index
    @date = params[:date] ? Date.parse(params[:date]) :  Date.today
    @datetime = DateTime.now.change({:year => @date.year, :month => @date.month, :day => @date.day, :hour => Time.now.hour, :min => Time.now.min})
    @trainings = current_user.trainings.where('start BETWEEN ? AND ?', Date.parse(params[:date]).beginning_of_day, Date.parse(params[:date]).end_of_day).order(:start)
    @training = Training.new
    @training_exercise = TrainingExercise.new
    @daily_exercises = current_user.daily_exercises.where('datetime BETWEEN ? AND ?', @date.beginning_of_day, @date.end_of_day)
    @daily_exercise = DailyExercise.new
  end

  def show
    begin
      @training = Training.find(params[:id])
    rescue
      @errors = ["There is no trainnig with id #{params[:id]}"]
    end
  end

  def destroy
    Training.find(params[:id]).destroy
  end

  private

  def training_params
    params.require(:training).permit(:description, :length, :start)
  end
end

app/controllers/wiki_controller.rb
class WikiController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sun Mon Tue Wed Thu Fri Sat]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "day" if day.month == date.month
      classes << "today" if day == Date.today
      classes << "selected_day" if day == date
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
   def resource_name
     :user
   end

   def resource
     @resource ||= User.new
   end

   def devise_mapping
     @devise_mapping ||= Devise.mappings[:user]
   end
end

app/helpers/repeats_helper.rb
module RepeatsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/trainings/_training.html.haml
- training_exercises = TrainingExercise.where(:training_id => training.id)
.accordion{:id => "training#{training.id}"}
  .accordion-group
    .accordion-heading
      .training-header
        %a{:class => 'accordion-toggle span4', 'data-toggle' => 'collapse', :href => "#collapse#{training.id}"}
          = "Training - #{training.start.hour}:#{training.start.min}"
        <!-- .span6.training-header-description= training.description -->
        .span6
        .span2.training-options
          %a.icon-repeat{"data-toggle" => "modal", :href => "#repeatModal#{training.id}", :role => "button", title: 'Repeat training', rel: 'tooltip'}
          = render :partial => 'layouts/repeat_modal', :locals => {:training => training}
          = link_to '', training_path(training), :class => 'icon-share', title: 'Pulic link', rel: 'tooltip'
          = link_to '', user_training_path(current_user, training), data: { confirm: 'Are you sure?' }, :method => :delete, remote: true, :class => 'icon-trash', title: 'Delete training', rel: 'tooltip'
      %div{:id => "collapse#{training.id}", :class => 'accordion-body collapse'}
        .accordion-inner
          .h3 Description:
          .p= training.description
          .push
          %table.table.training-table{:id => "exercise#{training.id}"}
            - if not training_exercises.empty?
              = render 'training_exercises/training_table_header'
            %tbody
              - training_exercises.each do |exercise|
                = render exercise
          = form_for :exercise, :url => training_exercises_path(:training_id => training.id), remote: true, html: {:class => 'form-inline'} do |f|
            = f.text_field :id, :type => 'hidden', :class => 'exerciseId'
            = f.text_field :name, :class => 'add_training_exercise span12', :autocomplete => 'off', :placeholder => 'Element name'
            = f.text_area :description, :placeholder => 'Description', :class => 'exerciseDesc span12'
            = f.text_field :apparatus, :class => 'exerciseApparatus input-small', :placeholder => 'Apparatus', data: {autocomplete_source: Apparatus.order(:name).map(&:name)}
            .input-append
              = f.number_field :load, :placeholder => 'Load', :min => 0, :class => 'exerciseLoad input-mini'
              %span.add-on kg
            = f.check_box :hold, :class => 'te-cb'
            = f.number_field :number_of_reps_in_set, :min => 0, :placeholder => 'Reps', :class => 'exerciseReps input-mini'
            .input-append.te-len
              = f.number_field :length, :min => 0, :placeholder => 'Length', :class => 'exerciseLength input-mini'
              %span.add-on sec
            = f.number_field :number_of_sets, :min => 0, :placeholder => 'Sets', :class => 'exerciseSets input-mini'
            = f.button :Add, :class => 'btn'

app/views/trainings/create.html.haml
<h1>Trainings#create</h1>
<p>Find me in app/views/trainings/create.html.erb</p>

app/views/trainings/destroy.js.erb
$('#training<%= params[:id] %>').remove();

app/views/trainings/edit.html.haml
<h1>Trainings#edit</h1>
<p>Find me in app/views/trainings/edit.html.erb</p>

app/views/trainings/index.html.haml
.push
.accordion#accordion2
  .accordion-group
    .accordion-heading
      %a{:class => 'accordion-toggle', 'data-toggle' => 'collapse', :href => '#collapseNew'} Create new training
      %div{:id => 'collapseNew', :class => 'accordion-body collapse'}
        .accordion-inner
          = form_for :training, :url => user_trainings_path do |f|
            %p
              #datetimepicker1.input-append.date.span12
                = f.text_field :start, 'data-format' => 'dd-MM-yyyy hh:mm:ss', :value => @datetime.strftime('%d-%m-%Y %H:%M:%S'), :class => 'span11'
                %span.add-on
                  %i{'date-time-icon' => 'icon-time', 'data-date-icon' => 'icon-calendar'}
            .input-append.span12
              = f.number_field :length, :min => 0, :placeholder => 'Length', :class => 'span11'
              %span.add-on min
            %p
              .span12
                = f.text_area :description, :placeholder => 'Description', :class => 'span12'
            %p= f.button :create, :class => 'btn'
= render @trainings
= render 'layouts/daily_training'

app/views/trainings/new.html.haml
<h1>Trainings#new</h1>
<p>Find me in app/views/trainings/new.html.erb</p>

app/views/trainings/show.html.haml
.span3
.span6
  - if @training
    - training_exercises = TrainingExercise.where(:training_id => @training.id)
    = "Training - #{@training.start.hour}:#{@training.start.min}"
    %table.table
      %thead
        %tr
          %th Name
          %th Load
          %th Reps
          %th Sets
          %th Done
      %tbody
        - training_exercises.each do |te|
          %tr{:class => "#{'done' if te.done}"}
            - ex = te.exercise
            %td= te.exercise.element.name
            %td
              - load = ex.load
              = load == 0 ? '-' : "#{load} kg"
            %td= ex.number_of_reps_in_set
            %td= ex.number_of_sets
            %td.done-cell
              %i{:class => "#{'icon-ok' if te.done}"}
  - else
    = render 'layouts/errors'