config/routes.rb
DrillsBook::Application.routes.draw do

  get "repeats/create"
  get "home/index"
  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'users/:user_id/trainings/:date', to: 'trainings#index', date: /\d{4}-\d{2}-\d{2}/
  get 'trainings/:id', to: 'trainings#show', as: 'training', id: /\d+/

  resources :repeats, only: :create
  resources :daily_exercises, except: [:show, :edit, :update]

  resources :users do
    resources :trainings, except: :show
  end
  resources :training_exercises
  resources :exercises, path: 'wiki/exercises'
  resources :elements, path: 'wiki/elements'

  root 'home#index'

  

end

app/models/apparatus.rb
class Apparatus < ActiveRecord::Base
  has_many :exercises

  validates :name, :uniqueness => true
end

app/models/category.rb
class Category < ActiveRecord::Base
    has_and_belongs_to_many :elements
end

app/models/daily_exercise.rb
class DailyExercise < ActiveRecord::Base
    belongs_to :user
    belongs_to :exercise
end

app/models/element.rb
require 'file_size_validator'
class Element < ActiveRecord::Base
    before_validation :default_values
    has_many :exercises
    has_and_belongs_to_many :categories
    has_and_belongs_to_many :muscle_groups
    belongs_to :user
    belongs_to :scope
    mount_uploader :image, ImageUploader
    validates :image,
        :presence => false,
        :file_size => { :maximum => 1.megabytes.to_i }

    def default_values
        self.scope_id ||= Scope.where(:name => 'user_private').first.id
        self.description ||= ''
    end
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  before_validation :default_values
  has_many :training_exercises, dependent: :destroy
  has_many :daily_exercises, dependent: :destroy
  has_many :trainings, through: :training_exercises
  belongs_to :element
  belongs_to :user
  belongs_to :apparatus

  def self.get_or_create_by(user, element_name, apparatus_name, options = {})
    element = Element.find_or_create_by(name: element_name)
    apparatus = Apparatus.where(name: apparatus_name).first
    if options[:hold] == '1'
      options[:hold] = true
    elsif
      options[:hold] = false
    end
    options[:user_id] = user.id
    options[:element_id] = element.id
    options[:apparatus_id] = apparatus.id
 #   Exercise.where(options).first
    Exercise.find_or_create_by(options)
  end

  def element_name
    element.try(:name)
  end

  def element_name=(name)
    if name.strip == ''
        return nil
    end
    self.element = Element.find_or_create_by(:name => name) if name.present?
  end

  def apparatus_name
    apparatus.try(:name)
  end

  def apparatus_name=(name)
    self.apparatus = Apparatus.where(:name => name).first if name.present?
  end

  def default_values
      self.load ||= 0
      self.length ||= 0
      self.number_of_reps_in_set ||= 0
      self.number_of_sets ||= 0
      self.description ||= ''
      self.hold ||= false
      true
  end
end

app/models/muscle.rb
class Muscle < ActiveRecord::Base
    has_and_belongs_to_many :muscle_groups
end

app/models/muscle_group.rb
class MuscleGroup < ActiveRecord::Base
    has_and_belongs_to_many :muscles
    has_and_belongs_to_many :elements
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users

  validates :name, :uniqueness => true
end

app/models/scope.rb
class Scope < ActiveRecord::Base
  has_many :elements

  validates :name, :uniqueness => true
end

app/models/training.rb
class Training < ActiveRecord::Base
    has_many :training_types
    has_many :training_exercises, dependent: :destroy
    has_many :exercises, through: :training_exercises
    belongs_to :user
end

app/models/training_exercise.rb
class TrainingExercise < ActiveRecord::Base
    belongs_to :training
    belongs_to :exercise
end

app/models/training_type.rb
class TrainingType < ActiveRecord::Base
    has_and_belongs_to_many :trainings
end

app/models/user.rb
class User < ActiveRecord::Base
  before_validation :default_values
  has_many :trainings
  has_many :exercises
  has_many :elements
  has_many :daily_exercises, dependent: :destroy
  belongs_to :role

  validates :role, :presence => true

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def default_values
    self.role_id ||= Role.where(:name => 'user').first.id
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sun Mon Tue Wed Thu Fri Sat]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "day" if day.month == date.month
      classes << "today" if day == Date.today
      classes << "selected_day" if day == date
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/home_helper.rb
module HomeHelper
   def resource_name
     :user
   end

   def resource
     @resource ||= User.new
   end

   def devise_mapping
     @devise_mapping ||= Devise.mappings[:user]
   end
end

app/helpers/repeats_helper.rb
module RepeatsHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/layouts/_calendar.html.haml
%h4.center#month
  = link_to '', user_training_path(current_user, @date.prev_month), :class => 'icon-chevron-left'
  = @date.strftime("%B %Y")
  = link_to '', user_training_path(current_user, @date.next_month), :class => 'icon-chevron-right'
#trainings
  = calendar @date do |date|
    %div
      = link_to '', user_training_path(current_user, date) if date.month == @date.month
      = date.day

app/views/layouts/_daily_training.html.haml
.accordion
  .accordion-group
    .accordion-heading
      %a.accordion-toggle{'data-toggle' => 'collapse', :href => '#collapseDaily'} Daily Exercises
      #collapseDaily.accordion-body.collapse
        .accordion-inner
          %table.table#daily-exercises-table
            - if not @daily_exercises.empty?
              = render 'daily_exercises/exercises_table_header'
            %tbody
              - @daily_exercises.each do |daily_exercise|
                = render daily_exercise
          = form_for :exercise, :url => daily_exercises_path(:date => params[:date]), remote: true, html: {:class => 'form-inline'} do |f|
            = f.text_field :id, :type => 'hidden', :class => 'exerciseId'
            = f.text_field :name, :class => 'add_training_exercise span12', :autocomplete => 'off', :placeholder => 'Element name'
            = f.text_area :description, :placeholder => 'Description', :class => 'exerciseDesc span12'
            = f.text_field :apparatus, :class => 'exerciseApparatus input-small', :placeholder => 'Apparatus', data: {autocomplete_source: Apparatus.order(:name).map(&:name)}
            .input-append
              = f.number_field :load, :placeholder => 'Load', :min => 0, :class => 'exerciseLoad input-mini'
              %span.add-on kg
            = f.check_box :hold, :class => 'te-cb'
            = f.number_field :number_of_reps_in_set, :min => 0, :placeholder => 'Reps', :class => 'exerciseReps input-mini'
            .input-append.te-len
              = f.number_field :length, :min => 0, :placeholder => 'Length', :class => 'exerciseLength input-mini'
              %span.add-on sec
            = f.number_field :number_of_sets, :min => 0, :placeholder => 'Sets', :class => 'exerciseSets input-mini'
            #timepickerDaily.input-append.time
              = f.text_field :time, 'data-format' => 'hh:mm:ss', :value => Time.now.strftime('%H:%M:%S'), :class => 'input-small'
              %span.add-on
                %i{'date-time-icon' => 'icon-time', 'data-date-icon' => 'icon-calendar'}
            = f.button :Add, :class => 'btn'

app/views/layouts/_elements.html.haml
.span3
  .well.sidebar-nav
    %ul.nav.nav-list
      %li.nav-header Sportovi
      %li Gimnastika
      %li Sinkro
      %li Nogomet
      %li.nav-header Tip
      %li Snaga
      %li Fleksibilnost
      %li Vjestina
.span6
  .well
    = yield

app/views/layouts/_errors.html.haml
- @errors.each do |message|
  %p.error= message

app/views/layouts/_exercises.html.haml
.span3
  .well.sidebar-nav
    %ul.nav.nav-list
      %li.nav-header Sportovi
      %li Gimnastika
      %li Sinkro
      %li Nogomet
      %li.nav-header Tip
      %li Snaga
      %li Fleksibilnost
      %li Vjestina
.span6
  .well
    = yield

app/views/layouts/_footer.html.haml
.container
  .company
    %p.muted.credit After Infinity Studio 2013
  .infolinks
    %ul.lista
      %li
        %a About
      %li
        %a Contact

app/views/layouts/_home.html.haml
= yield

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"
  - elsif msg.is_a?(Array)
    - msg.each do |m|
      %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
        %a.close{"data-dismiss" => "alert"} ×
        = content_tag :div, m, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%li= link_to 'DrillsBook', root_path, :class => 'brand'
- if user_signed_in?
  %li= link_to 'Trainings', user_training_path(current_user, Date.today), :class => 'brand'
  %li.dropdown
    %a.dropdown-toggle.brand#dLabel{"data-toggle" => "dropdown", :href => "#", :role => 'button'}
      Wiki
      %b.caret
    %ul.dropdown-menu{"aria-labelledby" => "dLabel", :role => "menu"}
      %li= link_to 'Exercises', exercises_path, :role => 'menuitem'
      %li= link_to "Elements", elements_path, :role => 'menuitem'

app/views/layouts/_registrations.html.haml
= render "devise/registrations/#{params[:action]}" unless params[:action] == 'create'

app/views/layouts/_repeat_modal.html.haml
.modal.hide.fade{:id =>"repeatModal#{training.id}", "aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Repeat training
  .modal-body
    = form_for :repeat, :url => repeats_path, remote: true, :html => {:class => 'form-horizontal'} do |f|
      = f.text_field :training_id, :type => 'hidden', :value => training.id
      .control-group
        = f.label 'Repeats:', :class => 'control-label'
        .controls= f.select :type, [['Daily', 1], ['Weekly', 2]], {}, {:class => 'input-small repeat-type'}
      .control-group.daily
        = f.label 'Repeat every:', :class => 'control-label'
        .controls
          .form-inline
            = f.select :days, [1,2,3,4,5], {}, {:class => 'input-mini'}
            = f.label 'days'
      .weekly
        .control-group
          = f.label 'Repeat every:', :class => 'control-label'
          .controls
            .form-inline
              = f.select :weeks, [1,2,3,4], {}, {:class => 'input-mini'}
              = f.label 'weeks'
            = f.check_box :sunday
            = f.label :sunday, 'S', :class => 'checkbox inline'
            = f.check_box :monday
            = f.label 'M', :class => 'checkbox inline'
            = f.check_box :tuesday
            = f.label 'T', :class => 'checkbox inline'
            = f.check_box :wednesday
            = f.label 'W', :class => 'checkbox inline'
            = f.check_box :thursday
            = f.label 'T', :class => 'checkbox inline'
            = f.check_box :friday
            = f.label 'F', :class => 'checkbox inline'
            = f.check_box :saturday
            = f.label 'S', :class => 'checkbox inline'
      .control-group
        = f.label 'Starts on:', :class => 'control-label'
        .controls
          .startdatepicker.input-append.date
            = f.text_field :start_date, 'data-format' => 'dd-MM-yyyy', :value => training.start.to_date.strftime('%d-%m-%Y'), :class => 'input-small'
            %span.add-on
              %i{'date-time-icon' => 'icon-time', 'data-date-icon' => 'icon-calendar'}
      .control-group
        = f.label 'Ends:', :class => 'control-label'
        .controls
          .form-inline.after-rb
            = f.radio_button :after, 'true', :checked => true, :class => 'inline'
            = f.label 'after'
            = f.number_field :repeat_after, :min => 0, :class => 'input-mini'
            = f.label 'occurrences'
          .form-inline.on-rb
            = f.radio_button :on, 'false'
            = f.label 'on'
            .enddatepicker.input-append.date
              = f.text_field :end_date, 'data-format' => 'dd-MM-yyyy', :value => training.start.to_date.strftime('%d-%m-%Y'), :class => 'input-small'
              %span.add-on
                %i{'date-time-icon' => 'icon-time', 'data-date-icon' => 'icon-calendar'}
  .modal-footer
    %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close
    %button.btn.btn-primary.repeat-submit Repeat

app/views/layouts/_trainings.html.haml
- if params[:action] == 'show'
  = yield
- else
  .content-fluid
    .row-fluid
      .span3
        .sidebar-nav
          = render 'layouts/calendar'
          .push
      .span6
        = yield
      .span3
        .sidebar-nav
          %ul.nav.nav-list
            %li.nav-header Statistike

app/views/layouts/_user.html.haml
- if user_signed_in?
  %ul.nav.span3.pull-right
    %li.dropdown
      %a.dropdown-toggle.brand#userLabel{"data-toggle" => "dropdown", :href => "#", :role => 'button'}
        #{current_user.email}
      %ul.dropdown-menu{"aria-labelledby" => "userLabel", :role => 'menu'}
        %li= link_to 'Edit', edit_user_registration_path, :role => 'menuitem'
        %li= link_to 'Log out', destroy_user_session_path, :method => :delete, :role => 'menuitem'
- else
  %ul.nav.span6.pull-right
    = form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f|
      = f.email_field :email, :autofocus => true, :placeholder => 'Email'
      = f.password_field :password, :placeholder => 'Password'
      = f.check_box :remember_me
      = f.submit 'Sign in', :class => 'btn btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "DrillsBook"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
  %body
    #wrap
      %header.navbar.navibar-inverse.navbar-fixed-top
        %nav.navbar-inner
          .container
            %ul.nav.span5{:role => 'navigation'}
              = render 'layouts/navigation'
            = render 'layouts/user' if params[:controller] != 'session'
      #main{:role => "main"}
        .container
          .container-fluid
            .row-fluid.no-space
              = render 'layouts/messages'
              = render "layouts/#{params[:controller]}"
    %footer#footer
      .container
      = render 'layouts/footer'
    .span1
    .span10
      = debug(params) if Rails.env.development?